### PR TITLE
Add sql syntax highlight

### PR DESCRIPTION
**Pull request by nickynicolson**
Added markdown flags to indicate code blocks contain SQL, ie eligible for SQL syntax highlighting.

### CODE REVIEW

**Comment by ethanwhite** [comment]
Thanks @nickynicolson!

**Comment by ethanwhite** [comment]
Looks like I should have tested this. The loss of blank lines appears to have caused the github pages site to lose all of the related line breaks. I'm going to revert this.

**Comment by nickynicolson** [comment]
I'll get Jekyll set up locally so I can work this out.

**Comment by ethanwhite** [comment]
Great thanks - I suspect that all we need is to put the blank lines back in. Sorry I didn't catch it before merging and thanks for your help.

**Pull request merged**
