### PR TITLE
Introduced 'USING'

### PR DESCRIPTION
**Pull request by c-martinez**
As discussed in PR #67 , the key word `USING` is introduced in the lesson.

I've decided to introduce `USING` first, and then `ON` as an alternative when column names do not match. This seems more logical to me, but it could also be the other way around. What do you think @ethanwhite @waveform80 ?

### CODE REVIEW

**Comment by waveform80** [comment]
It's a nice idea, but given that USING isn't universally implemented (while ON is, although they're both "standard" SQL), I'm a bit nervous about introducing it first (at the very least, we'd need to stress that users may find USING unsupported).

I'd say that ON is considered the "canonical" method of specifying JOIN criteria and USING is regarded as a convenient short-hand. But from my experience, it's quite rarely used in practice (even in those engines that support it), although I'm not sure why. Possibly because having common column names isn't actually *that* common in real-world schemas, or perhaps it's just users' ignorance of the facility?

**Comment by ethanwhite** [comment]
Thanks @c-martinez. I agree with @waveform80 that the existing introduction of `ON` should remain first and then a one or two sentence note about `USING` added after it.

**Comment by c-martinez** [comment]
Ok, how about this then?

**Comment by ethanwhite** [comment]
Looks great. Thanks @c-martinez!

**Comment by waveform80** [comment]
Looks good to me! The only thing I'd add is perhaps a sentence like "while USING is standard SQL and widely supported, a few engines don't implement it; if you get a syntax error with USING, you may want to fall-back to ON for debugging". I've done a quick check on exactly which engines do/don't support USING (my memory's more than a little rusty on some of these engines!) and the tally is as follows:

Supported:
* MySQL
* PostgreSQL
* SQLite
* Firebird (since 2.5 at least, so I was wrong on that one)
* Oracle

Unsupported
* DB2
* MS-SQL Server

So, it's definitely widely supported, and I suspect most scientists won't encounter an engine where it isn't supported (DB2's pretty rare outside of banks / multi-nationals, although MS-SQL Server is quite widely used in smaller organisations; I can imagine some universities might favour it).

**Comment by waveform80** [comment]
Heh - merged as soon as I posted that comment - don't worry about adding that sentence; the unsupported engines are rare enough that it's probably not worth it

**Comment by ethanwhite** [comment]
Yeah, definitely a bit of a race condition there :) Thanks for the feedback on this @waveform80.

**Pull request merged**
