### PR TITLE
Marking the sql.md as obsolete file

### PR DESCRIPTION
**Pull request by apawlik**
Marking the old teaching material file sql.md as obsolete to avoid confusion in the future (as suggested by @waveform80 )

### CODE REVIEW

**Comment by ethanwhite** [comment]
Is there any reason not to simply delete this instead?

**Comment by apawlik** [comment]
I don't know. So I thought I'd rather not delete in case it turns out I again missed something.

**Comment by ethanwhite** [comment]
I think we should just delete this instead.

**Comment by waveform80** [comment]
Yup, just delete it - you can always pull it back from the git history if need be

**Comment by apawlik** [comment]
I'll delete in my branch and the PR should then update.

**Comment by apawlik** [comment]
Hope this will be allright now. Thanks @ethanwhite and @waveform80 !

**Comment by ethanwhite** [comment]
Looks great. Thanks @apawlik!

**Pull request merged**
