### PR TITLE
Updated link to the Portal Database

### PR DESCRIPTION
**Pull request by tracykteal**

### CODE REVIEW

**Comment by ethanwhite** [comment]
Any reason not to link to the new Portal Teaching Database on figshare:
http://files.figshare.com/1919744/surveys.csv

and get rid of the data folder entirely?

**Comment by ethanwhite** [comment]
Oops, wrong link:
http://files.figshare.com/1919743/portal_mammals.sqlite

**Comment by tracykteal** [comment]
I think that's preferred, as long as that dataset matches the lesson.

**Comment by ethanwhite** [comment]
Ah right. There are a few things to clean up there. I'll go ahead and merge this so that's it's correct now and then open an issue and try to clean this up soon. Thanks!

**Pull request merged**
