### PR TITLE
Rephrased references to Python & added lesson layout

### PR DESCRIPTION
**Pull request by apawlik**
I removed the explicit references to Python as they are confusing and irrelevant.
I also added the lesson layout (so that the lessons are displayed like http://apawlik.github.io/sql-ecology/). The reason why the lesson layout is not showing in commits is probably because I created this PR previously, merged myself (in a rush to have things ready for Utrecht) and then reverted the merge - as @hlapp righteously pointed out that someone else should review and merge. Summarizing, the main changes are the Python references and the lesson layout.
I think even if the lesson template changes, it's worth to get most of our lessons in a lesson template so that they render nicely. They can be updated if needed with new template in the future.

### CODE REVIEW

**Comment by ethanwhite** [comment]
The changes to the lesson look great. I totally agree on the template, but I'd be surprised if this actually merged those in given the diff. One way to find out :)

**Comment by ethanwhite** [comment]
Yep, none of the templating is here. I'm happy to quickly review and merge a PR with it included.

**Comment by apawlik** [comment]
Meh. Stupid GitHub. Retrying soon.

**Comment by apawlik** [comment]
@ethanwhite I left a comment under the revert PR. The problem is that if I update my fork now from the original repo, all of templating is gone

**Pull request merged**
