### PR TITLE
Add sql syntax highlight

### PR DESCRIPTION
**Pull request by nickynicolson**
Tested with a local Jekyll install (had to add pygments css and reference from header.html).

### CODE REVIEW

**Comment by ethanwhite** [comment]
Thanks @nickynicolson. This yields different highlighting than I was expecting.

Here's the version from my local test:

screenshot from 2015-11-30 09 21 12

You can see that it sometimes highlights selected fields and sometimes doesn't.

Here's the highlighting of the same file on Github:

screenshot from 2015-11-30 09 25 39

This looks like what I was expecting.

My current take is that inconsistently highlighting selected fields is actually more confusing than not having syntax highlighting, especially given that capitalization is already being used to emphasize SQL commands.

Thoughts?

**Comment by nickynicolson** [comment]
I think pygments treats year/month/day as tokens in its SQL lexer (see https://pygments-doc.readthedocs.org/en/latest/_modules/pygments/lexers/sql.html#SqlLexer) - and as the example (quite reasonably) has uses year / month / day as column names, this causes the difference between the highlighting shown in github and that show when jekyll serves the pages. 

I agree that inconsistent highlighting is more confusing than none at all.

**Comment by ethanwhite** [comment]
Ah, that makes sense. I was definitely confused about why it was highlighting some fields and not others.

Would you like me to leave this open for the moment or close it and reopen it later if we figure out how to work around this?

**Comment by waveform80** [comment]
I'm afraid year, month, and day are reserved words in the SQL standard (although most implementations still allow their use as identifiers); in at least one implementation (DB2) ["labelled durations"](http://www-01.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.sql.ref.doc/doc/r0023457.html?cp=SSEPGG_10.5.0%2F2-12-2-10-0) are supported for arithmetic involving datetime values. For example:

```sql
SELECT some_date_column + 1 MONTH - 1 YEAR
FROM some_table
```

This is one of the reasons I generally discourage people from using year and month as column names (in addition to being confusing in DB2's case some other databases include similarly named functions for extracting the components of date fields). The other reason being that it's generally much easier to work with a single column of one of the date-time types (DATE, TIME, TIMESTAMP) directly rather than trying to make multiple integer columns fit the bill.

Not that any of this particularly helps in this case, but it might serve to explain pygments' behaviour here!

**Comment by ethanwhite** [comment]
Thanks for the additional explanation @waveform80! Given that these names are part of the overarching ecology dataset and would require100s of changes throughout multiple lessons I think for the moment we'll just need to close this and live without the syntax highlighting for the time being.

Thanks again to everyone for their contributions of both improvements and my understanding of SQL/highlighters!

**Pull request closed without merging**
