### PR TITLE
Split lessons

### PR DESCRIPTION
**Pull request by apawlik**
Splitted material into lessons, added a couple of challenges and instruction how to save queries in SQLite

### CODE REVIEW

**Comment by ethanwhite** [comment]
Thanks @apawlik! In general this looks really good. There are two things I think we should change before merging:

1. All of the material starting at Line 141 in `00-sql-introduction.md` is really supplemental material. I think we should split it into a separate file or leave it out of this structure to avoid folks thinking that this should be taught right up front.
2. I think 'aggregation' and 'joins + aliasing' should be two separate lessons.

**Comment by ethanwhite** [comment]
Closing since #34 (an exact copy of this PR) has now been merged.

**Comment by apawlik** [comment]
Ouch! I'm just about to push changes :-(

**Comment by ethanwhite** [comment]
Sorry about that. I should have given you a chance to tell me to wait (just had 30 minutes and figured I'd get it off your plate before running out the door). I owe you a beer the next time we're in the same place.

**Comment by apawlik** [comment]
I'm just confused about the workflow :-( Should I just abandon this split? Do we then keep everything in one md file?

**Comment by ethanwhite** [comment]
No, definitely not, I merged your other PR which was identical and the made the changes I'd asked for myself in #39.

**Comment by ethanwhite** [comment]
The other PR was #34.

**Comment by apawlik** [comment]
Thanks @ethanwhite ! Guess I can't use GitHub :-(

**Comment by ethanwhite** [comment]
No, not at all :) I just rushed things this morning and that made everything confusing.

Also, if you'd prefer to submit the changes you were about to push as a new PR I'd be happy to close #39 and take yours instead.

**Comment by apawlik** [comment]
I pushed in - added 00-supplement... but decided to keep info about data types in the 00-lesson... it's really useful to have it and show it to students.

**Comment by apawlik** [comment]
I'm now working on 'aggregatioon and joins' and pushing it soon.

**Comment by apawlik** [comment]
FInally incorportated @ethanwhite comments :/

**Comment by ethanwhite** [comment]
You'll need to submit a new PR from that branch since this has already been merged.

**Pull request closed without merging**
