### PR TITLE
Added css and layout info + 1 fix in the lesson

### PR DESCRIPTION
**Pull request by lwasser**
This commit adds the gh-pages materials needed to build a jekyll html version of our md files. There is one small change to the SQL.md lesson where the column heading is species and not species_id in the data provided to the students.

### CODE REVIEW

**Comment by ethanwhite** [comment]
My impression from https://github.com/datacarpentry/lesson-template/issues/1 had been that we were planning on getting this general material all worked out in https://github.com/datacarpentry/workshop-template before adding it to the individual repos. If I misunderstood I'm happy to review this here.

**Comment by ethanwhite** [comment]
@lwasser & @tracykteal - should I merge this in or wait for a PR based on https://github.com/datacarpentry/lesson-template ?

**Comment by lwasser** [comment]
Hi @ethanwhite sorry about the delayed response. i'd suggest waiting and as such i'll close this. there are two broader issues that we need to address.

1. someone should take the lead on the lesson template and then we can all use the same template! the SWC looks very nice. that could be a starting place even though they don't use jekyll.

2. the data that we are using is slightly different between the repos. some lessons (like this one) points to your figshare dataset. which is great. However, the python lessons have the data stored locally in the repo. There is some justification for this. In the merge data lesson, there are column headings that are intentionally different that makes the learners think about the value of consistency in headings when storing data AND also that inconsistency leads to a duplicate column name when merging. It's useful. 

When i made edits to your sql lesson, i edited some of the column names assuming the python lesson data were a mirror only to realize the data are different. 

We should sort this out throughout the DC repo before modifying your repo.

**Comment by ethanwhite** [comment]
> someone should take the lead on the lesson template and then we can all use the same template! the SWC looks very nice. that could be a starting place even though they don't use jekyll.

Any interest in taking the job :smile:?

> However, the python lessons have the data stored locally in the repo. There is some justification for this. In the merge data lesson, there are column headings that are intentionally different that makes the learners think about the value of consistency in headings when storing data AND also that inconsistency leads to a duplicate column name when merging. It's useful. 

We'd be open to adding a "messy" version of the dataset to the figshare database if we can agree on the kinds of messy things we want included.

**Comment by lwasser** [comment]
Hi -- if it doesn't have to happen quickly, i'd be happy to take the lead on a lesson template. I enjoy playing with css but would try to engage a few others. Do you happen to know who handles the SWC styling? 

Can we start an issue on the data somewhere? what is the protocol? i haven't seen the R lessons yet but will given i'm teaching them with tracy next week and will have more insight then.  I can tell you what i'd like to see for the python lessons in terms of a messy dataset. 

It would be IDEAL to have them all in once place so if you can make that happen, let's push this forward so we have uniformity across all R and python lessons. 

Once we get that setup, we'd need to tweak the python lessons just a bit. i'm sure i can get someone to help with that.

**Comment by tracykteal** [comment]
I have put together lesson templates in https://github.com/datacarpentry/lesson-template

They're similar to the SWC ones but use Jekyll rather than pandoc. The question though is if we should use the SWC template for consistency. There's good documentation now on how to use those templates, and it would make our lessons more interchangeable. 

I worry that using pandoc reduced people's ability to be lesson developers, but I think the good documentation is helping, and once the lesson framework is up, people can contribute via github web or something like Authorea.  Can we continue this discussion over on the lesson-template repo? I agree we need to come to a decision, and the sooner the better.

**Comment by ethanwhite** [comment]
Yes, let's move the issues to appropriate places. Probably a new issue for messy data in https://github.com/datacarpentry/planning and the lesson-template repo for more discussion over there.

**Pull request closed without merging**
