### PR TITLE
Views in 02

### PR DESCRIPTION
**Pull request by tpoisot**
I'm opening this PR so that we can track and discuss the progress on adding information about views.

- [x] remove the section on saving queries from lesson 1
- [x] add a section about views in lesson 2
   - [x] create a view
   - [x] delete a view
   - ~~update data through a view~~

### CODE REVIEW

**Comment by tpoisot** [comment]
**QUESTION**

Should we talk about updating the DB through a view? I think it's powerful but potentially dangerous. Ideas?

**Comment by ethanwhite** [comment]
> Should we talk about updating the DB through a view? I think it's powerful but potentially dangerous. Ideas?

I would vote no on this with the goal of simplicity.

**Comment by tpoisot** [comment]
I agree with @ethanwhite  -- what about you, @tracykteal  ?

Also happy to take feedback on the current changes.

**Comment by waveform80** [comment]
> > Should we talk about updating the DB through a view? I think it's powerful but potentially dangerous. Ideas?

> I would vote no on this with the goal of simplicity.

I agree entirely that updating views is well beyond the scope of the course (and thus shouldn't be included). Just one question though: why are they considered potentially dangerous?

(Background: I've used writeable views a fair bit in corporate life, up to and including instead-of triggers for re-writing statements to enable complex views incorporating joins to be writeable. I'd wholeheartedly agree that instead-of triggers can be horrendously dangerous, but I get the impression those aren't what's being talked about here. Without such triggers, writeable views tend to be restricted to frankly trivial queries - un-joined with simple WHERE clauses and no aggregation - unless there's something I've missed?)

**Comment by tpoisot** [comment]
@waveform80 I think the risk has more to do with using them when they should not be used -- I know people that do everything through views out of convenience, and it's just not a healthy habit. So for inexperience users of SQL (and this includes myself of course), I think it's safer/mare more sense to say "views are a way to view your data according to a query you already wrote".

**Comment by tpoisot** [comment]
@ethanwhite since we're not going to add anything about editing through views, I'm ok for this to be merged .

**Comment by ethanwhite** [comment]
OK, thanks. I'll try to give it a read later today or tomorrow.

**Comment by ethanwhite** [comment]
Thanks @tpoisot. This looks great!

Two questions and one small fix:

1. What was your thinking on putting the View piece in the middle? My initial reaction is that putting the entire query with the `ORDER BY` first and then making the view at the end would make it so that the initial query was fresh in the student's minds when the add the `ORDER BY` and they don't have to remember what they were doing after learning about views.

2. I like the focus on using SQL to create and view the queries since this will transfer generically to other SQL implementations, but I also think the GUI approaches can feel familiar for new learners. What do you think about adding a brief "You can also add a view using `Create View` in the `View` menu and see the results in the `Views` tab just like a table"?

3. The new code block should be one clause per line like the others.

**Comment by tpoisot** [comment]
1. The part before is about writing a reasonably complex query. So in a way, my thinking was "Hey, if you're going to need to do this more than once, you can save it as a view", and it would only add 5 minutes to the lesson. But I can move it to the end of the lesson.

2. Will do, as soon as I find a computer with firefox to see exactly how it's called.

3. My bad!

**Comment by tpoisot** [comment]
Hey, @ethanwhite -- what do you mean by 3, actually?
I only added the `CREATE VIEW...` line at the top, so it's one clause by line. Or am I missing something obvious?

**Comment by ethanwhite** [comment]
> Hey, @ethanwhite -- what do you mean by 3, actually?
> I only added the CREATE VIEW... line at the top, so it's one clause by line. Or am I missing something obvious?

Lines 89 and 90. Maybe it's the way the diff is displaying and it was actually my own bad habits :flushed:

**Comment by tpoisot** [comment]
No, that was me... It's fixed in the previous commit.

**Comment by ethanwhite** [comment]
> The part before is about writing a reasonably complex query. So in a way, my thinking was "Hey, if you're going to need to do this more than once, you can save it as a view", and it would only add 5 minutes to the lesson. But I can move it to the end of the lesson.

If you don't feel strongly about it I do prefer the end after reading this through a couple of times. Especially after adding the extra GUI material as well I think it will just feel like a long time since they wrote the query. Thanks!

**Comment by ethanwhite** [comment]
Last thing (hopefully, sorry):

1. It looks like the formatting on the last challenge is a little messed up (probably an overly aggressive reflow)
2. What do you think about leaving the last challenge at the very end and adding "Save this query as a view."

**Comment by tpoisot** [comment]
All of these are good ideas. I'll be on the lookout for aggressive reflows before the next commit (that will be when we're done appartment hunting).

**Comment by waveform80** [comment]
@tpoisot good point (re: people that do everything through views unnecessarily).

In industry, I've often advocated building views on top of tables even where it *seemed* unnecessary, simply because it allowed developers to mutate underlying table layouts, while using the view to provide a consistent interface to a downstream application (i.e. the view might start as a straight `SELECT fields FROM table` but might eventually become something more complex involving joins if the underlying table were broken into normalized pieces) - not to mention it allowed more possibilities with authorizations. However, I'd freely admit this probably isn't relevant to the audience of these workshops; my assumption is that most academic databases are simpler: they might serve several users, but they're not (usually) intended to serve multiple downstream applications with stable APIs over an extended period of time, and probably don't bother with lots of GRANTs.

Is it worth mentioning that `ORDER BY` is typically not allowed in view definitions? (I note you've excluded the `ORDER BY` in your view definition). SQLite does permit them (probably for compatibility with MySQL), but it's not permitted by the standard or supported by any other engines I'm aware of.

Also, is it worth mentioning that column names in views must be unique, while this doesn't apply to queries? This usually comes up when someone lazily tries to create a view of a `SELECT *` query involving joins between tables with equivalent column names. Given that this is before the joins section it may not be worth mentioning.

Those are the only two points I could think of - looking good otherwise!

**Comment by ethanwhite** [comment]
> Is it worth mentioning that ORDER BY is typically not allowed in view definitions?

Works fine for me in PostgresSQL, so if it also works in SQLite and MySQL/MariaDB I don't think we need to worry about it. This is for `SELECT * FROM TABLE`, but that's the level that we're teaching views at at this point. Regardless, this is getting too detailed in my opinion for folks seeing an SQL database for the first time.

**Comment by tpoisot** [comment]
Allright, I think it's done.

@waveform80 -- I agree with all your points but none of the learners are going to use SQL in an industry setting immediately after the workshop. This has a high risk of confusing them and putting them off SQL entirely, which is not what we want to do!

**Comment by ethanwhite** [comment]
Thanks @tpoisot. Looks awesome.

I'm super excited that you've offered to take over maintaining this material.

And with that, I will merge this and step out of the way to let you and Paula take over. Feel free to ping me if you have questions about anything. :wave:

**Comment by waveform80** [comment]
> > Is it worth mentioning that ORDER BY is typically not allowed in view definitions?

> Works fine for me in PostgresSQL, so if it also works in SQLite and MySQL/MariaDB I don't think we need to worry about it. This is for SELECT * FROM TABLE, but that's the level that we're teaching views at at this point. Regardless, this is getting too detailed in my opinion for folks seeing an SQL database for the first time.

Well I never - I thought this was a relatively well-adhered to bit of the standard, but it turns out it's not (not sure what I was thinking there). The big three commercial engines, DB2, MS-SQL and (partially) Oracle ban it, while all the open-source engines (SQLite, MySQL, PostgreSQL, and Firebird that I've tested) accept it. So definitely not worth mentioning!

> @waveform80 -- I agree with all your points but none of the learners are going to use SQL in an industry setting immediately after the workshop. This has a high risk of confusing them and putting them off SQL entirely, which is not what we want to do!

Agreed - best to keep things simple. And I'll echo @ethanwhite's words: looks great, many thanks!

**Comment by tpoisot** [comment]
By the way, @ethanwhite , can you or @tracykteal give Paula and I access to the repo?

**Comment by ethanwhite** [comment]
Oops, sorry about that. You're now an admin. I don't know Paula's username so I haven't added her yet, but fortunately you're an admin on the repo so if you know it you'll be all set to add her.

**Pull request merged**
