### PR TITLE
Update setup instructions

### PR DESCRIPTION
**Pull request by ethanwhite**
Update the setup instructions to work with newer versions of Firefox.

### CODE REVIEW

**Comment by tracykteal** [comment]
It might depend on the version of Firefox whether it's 'Tools' or 'Menu'. My version is still 'Tools'. Maybe we need a couple versions?

**Comment by ethanwhite** [comment]
I think these instructions will work on any recent version of Firefox, but may be the word 'menu' isn't sufficiently clear. On the far right of you screen you should see three horizontal lines. That's what I'm referring to as Menu in this case.

The challenge is that by default on some OSs Firefox won't show the top menu bar, so their won't be a visible `Tools` menu item. The other option would be to provide instructions for how to to show that standard menu bar (i.e., by pressing Alt). I'm happy with either.

**Comment by tracykteal** [comment]
Ah, right. I like the Menu terminology. Maybe we could add the part "on the far right there are three horizontal lines" so people know what the Menu is (including me apparently).

**Comment by ethanwhite** [comment]
Updated with a note on the three horizontal lines.

**Comment by ethanwhite** [comment]
@tracykteal - if this is ready to go please go ahead and merge it. Thanks.

**Comment by hlapp** [comment]
Shouldn't there be colons between the what to do and how to do it parts of each list item? It seems of the items changed, once includes the colon and two others don't. I'd put one there for each.

Also, aren't we now using the Portal dataset from Figshare?

**Comment by ethanwhite** [comment]
Colon changes added.

I'm working on the shift to the Portal dataset for a separate PR since it includes changes to column names that occur throughout the lesson.

**Pull request merged**
