### PR TITLE
added lesson for using R and SQL

### PR DESCRIPTION
**Pull request by emhart**
I've added a first draft of a lesson on using R and databases.  I tried to build off the existing curriculum using the Portal Mammals database.  My major goals were:

* Show students how to connect to an existing database
* Use `paste()` and R variables to construct queries and have integration with db queries and R variables
* Show students how to build databases using R as a workflow pipeline.

Is this too simple?  Should I have more examples with more complex queries?  Should I construct a more complicated database?  Other thoughts about how I could improve this lesson?

### CODE REVIEW

**Comment by lwasser** [comment]
i haven't looked at this closely yet BUT we have one for python now too that @qjcg created! https://github.com/datacarpentry/python-ecology/blob/gh-pages/08-working-with-sql.md 

should these live in this repo or in the python-ecology repo? i'm happy to have them here if everyone is ok with it!

**Comment by ethanwhite** [comment]
I don't have a feel strongly about this, but my initial inclination is that this kind of material should live in the R/Python repos since it's actually in those languages and since I believe the current strategy is to teach SQL early and then R/Python later.

Does anyone else have thoughts on where this material should go (including any of the @datacarpentry/owners).

**Comment by karthik** [comment]
@ethanwhite No strong feelings either, but I agree that these should reside in language specific repos.

**Comment by qjcg** [comment]
Agree with @ethanwhite and @karthik , I think the "X and SQL" material belongs in the language-specific lesson repos.

**Comment by emhart** [comment]
If that's the general feeling I'll close this PR and issue one in the R lesson.

**Comment by ethanwhite** [comment]
Thanks Ted.

**Pull request closed without merging**
