### PR TITLE
Comments in SQL

### PR DESCRIPTION
**Pull request by tpoisot**
As per #55 -- added a note on comments.
Also added some github markdown syntax to highlight the keywords and such in *some* blocks. Happy to do for all.

### CODE REVIEW

**Comment by ethanwhite** [comment]
Thanks @tpoisot!

We should definitely explicitly introduce comments in the material. The current demonstration feels a bit like [documenting mechanics instead of design & purpose](http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1001745#s8). What do you think about a comment at the top of the block like `Get post 2000 data on Dipodomys' species` instead?

There's actually a problem with adding highlighting unfortunately. See discussion in #60.

**Comment by tpoisot** [comment]
My my, what a terrible comment that was. I try to do a bit of both, i.e. usually start with a line or two about design / purpose, but leave notes for the mechanisms in the code itself. Especially when there are several ways to approach a problem, and I can't figure which one I thought was best 6 months ago.

**Comment by ethanwhite** [comment]
:smile: certainly there's value in documenting mechanics sometimes, this just seemed like a case where the comments were just restating the code, which I like to avoid modeling if possible.

If you can pull out the SQL highlighting I'm happy to take whatever version of the comment you want to go with.

**Comment by tpoisot** [comment]
:heavy_check_mark:

**Pull request merged**
