### PR TITLE
Add note that we are not walking through importing data

### PR DESCRIPTION
**Pull request by ethanwhite**

### CODE REVIEW

**Comment by hlapp** [comment]
Is this a lesson learned from teaching that stepping through the import is not useful?

**Comment by ethanwhite** [comment]
It's more of a timing issue. I don't typically teach the actual imports because there are really two choice:

1. Import everything starting from the csv files. This means importing 3 tables (which takes a few minutes) and there is a risk that if a student fails to get the types correct (I see this in a semester long course where they keep the string default for columns with numbers) than other exercises can break. 
2. Just start with an sqlite file

I still show them most of the steps to the import, but don't actually have them do it.

That said, since we're talking about often total novices and we're asking them to switch tools, I can very much see the argument for walking them through importing the surveys table and then having them import the species and plots tables as an exercise (I've actually done this before at one point).

Thoughts?

**Comment by hlapp** [comment]
I recall (perhaps wrongly) that we did walk students through the SQL import at the inaugural bootcamp. IRL learners will be faced with CSV or TSV files, not .sqlite databases. Therefore I would think that walking them through loading data into SQLite would be quite useful. Similarly, the git lesson at SWC starts with `git init`, followed by adding files to git (rather than cloning a repo that exists and has files in it).

**Comment by ethanwhite** [comment]
You're probably right. I've taught this material a bunch of times several different ways and can't recall which was when. I'm convinced by your argument, and it really only takes a couple of minutes, so I'm going to close this and leave it the way it is.

**Comment by ethanwhite** [comment]
Oh, and thanks a lot for all of the reviewing and merging today!

**Pull request closed without merging**
